name: CI
on: push

env:
  PNPM_VERSION: 9

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm start
      - run: pnpm test
