name: CI
on: push

env:
  PNPM_VERSION: 8

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [21]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm check
      - run: pnpm start
      - run: pnpm test
